spring:
  application:
    environment: development

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.yobel: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:DEBUG}
    org.springframework.data.r2dbc: ${LOG_LEVEL_R2DBC:DEBUG}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:INFO}
    reactor.netty: ${LOG_LEVEL_REACTOR:INFO}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:"*"}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:always}
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY:1.0}

cors:
  allowed-origins: ${CORS_ORIGINS:"*"}
  allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_HEADERS:"*"}
  max-age: ${CORS_MAX_AGE:3600}

server:
  error:
    include-message: ${ERROR_INCLUDE_MESSAGE:always}
    include-binding-errors: ${ERROR_INCLUDE_BINDING:always}
